def get_demo_findings():
    return [
        {
            "finding_id": "PRIV-DEMO-001",
            "created_at": "2026-05-08T12:00:00Z",
            "source_module": "Privacy Code Scanner",
            "title": "PII in logs",
            "description": "Application logging references customer email in plaintext.",
            "severity": "High",
            "severity_score": 3,
            "risk_area": "Logging control failure",
            "data_types": ["email"],
            "control_mapping": ["Logging control", "Data minimization", "Secure SDLC"],
            "recommended_remediation": "Mask or hash email before writing to logs.",
            "evidence_required": "Unit test showing sanitized logs and sample masked log output.",
            "owner": "Engineering",
            "status": "Open",
            "policy_decision": "Redact",
            "location": "Line 14",
        },
        {
            "finding_id": "PRIV-DEMO-002",
            "created_at": "2026-05-08T12:05:00Z",
            "source_module": "LLM Prompt Privacy Scanner",
            "title": "Social Security Number detected in LLM prompt",
            "description": "The prompt contains an SSN and should not be sent to an external LLM.",
            "severity": "Critical",
            "severity_score": 4,
            "risk_area": "Regulated identifier exposure",
            "data_types": ["ssn"],
            "control_mapping": [
                "Sensitive data handling",
                "Data loss prevention",
                "AI input governance",
            ],
            "recommended_remediation": "Block SSNs from external model calls and tokenize or remove from logs.",
            "evidence_required": "Policy decision log, redaction test, and blocked transmission evidence.",
            "owner": "AI Product / Privacy",
            "status": "Open",
            "policy_decision": "Block",
            "location": "Prompt body",
        },
        {
            "finding_id": "PRIV-DEMO-003",
            "created_at": "2026-05-08T12:10:00Z",
            "source_module": "Privacy Code Scanner",
            "title": "Unbounded retention",
            "description": "Code appears to persist customer support transcripts without retention metadata.",
            "severity": "Medium",
            "severity_score": 2,
            "risk_area": "Retention control gap",
            "data_types": ["customer_free_text"],
            "control_mapping": [
                "Retention management",
                "Data lifecycle governance",
                "Deletion controls",
            ],
            "recommended_remediation": "Add retention metadata, deletion logic, or an approved retention rule.",
            "evidence_required": "Retention rule, deletion test, and owner approval.",
            "owner": "Data Governance",
            "status": "In Progress",
            "policy_decision": "Warn",
            "location": "Line 27",
        },
        {
            "finding_id": "PRIV-DEMO-004",
            "created_at": "2026-05-08T12:15:00Z",
            "source_module": "LLM Prompt Privacy Scanner",
            "title": "Account Number Field detected in LLM prompt",
            "description": "The prompt references a financial account identifier.",
            "severity": "High",
            "severity_score": 3,
            "risk_area": "Regulated identifier exposure",
            "data_types": ["account_number"],
            "control_mapping": [
                "Sensitive data handling",
                "Data loss prevention",
                "AI input governance",
            ],
            "recommended_remediation": "Mask financial identifiers and restrict processing to approved systems.",
            "evidence_required": "Masking test and approved data-flow documentation.",
            "owner": "AI Product / Privacy",
            "status": "Open",
            "policy_decision": "Block",
            "location": "Prompt body",
        },
        {
            "finding_id": "PRIV-DEMO-005",
            "created_at": "2026-05-08T12:20:00Z",
            "source_module": "Privacy Code Scanner",
            "title": "Date of Birth Field detected in code",
            "description": "The code references date of birth, which may indicate overcollection.",
            "severity": "High",
            "severity_score": 3,
            "risk_area": "Sensitive data collection",
            "data_types": ["date_of_birth"],
            "control_mapping": [
                "Data minimization",
                "Purpose limitation",
                "Privacy review",
            ],
            "recommended_remediation": "Confirm full date of birth is required. Use age band or age verification flag when possible.",
            "evidence_required": "Data minimization rationale and product requirement approval.",
            "owner": "Product / Privacy",
            "status": "Open",
            "policy_decision": "Redact",
            "location": "Line 9",
        },
    ]